output   = "internal/core/domain/models"
wipe     = true

[psql]
dbname = "pasarin-reports"
user = "postgres"
pass = "postgres"
host = "localhost"
port = "5432"
sslmode = "disable"
blacklist = ["migrations"]