// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/pasarin-tech/base-go/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// EventService is an autogenerated mock type for the EventService type
type EventService struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: ctx, gtm
func (_m *EventService) CreateEvent(ctx context.Context, gtm *domain.EngagementRequest) error {
	ret := _m.Called(ctx, gtm)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.EngagementRequest) error); ok {
		r0 = rf(ctx, gtm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
